default: true

# Line length: allow longer lines for links and keep code blocks/tables exempt.
MD013:
  line_length: 120
  code_blocks: false
  tables: false
  headings: false

# Unordered list indentation style (2 spaces).
MD007:
  indent: 2

# Allow duplicate headings at different nesting levels.
MD024:
  siblings_only: true

# Allow bare URLs in text (we intentionally include full reference links).
MD034: false

# Do not require a language tag for fenced code blocks (we mix shell/JSON snippets).
MD040: false
