name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.11', '3.14' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Install project (dev)
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e .
          uv pip install ruff pyright pylint pytest
      - name: Print interpreter
        run: |
          source .venv/bin/activate
          python -c "import platform,sys;print(platform.python_build());print(sys.version)"
      - name: Check free-threading (best-effort)
        run: |
          source .venv/bin/activate
          python - <<'PY'
          import sysconfig
          print('Py_GIL_DISABLED =', sysconfig.get_config_var('Py_GIL_DISABLED'))
          PY
      - name: Ruff format + lint
        run: |
          source .venv/bin/activate
          ruff format --check .
          ruff check .
      - name: Pyright
        run: |
          source .venv/bin/activate
          pyright
      - name: Pylint
        run: |
          source .venv/bin/activate
          pylint src/exa_direct tests examples --fail-under=9.5 || true
      - name: Pytest
        run: |
          source .venv/bin/activate
          PYTHONPATH=src pytest -q
